# Generated by Django 3.0.5 on 2020-05-07 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receita', '0004_remove_receita_ingredientes'),
        ('ingrediente', '0003_remove_ingrediente_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceitaIngrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(choices=[('UN', 'unidade'), ('XICARA', 'xícara'), ('TSP', 'colher de chá'), ('TBSP', 'colher de sopa'), ('G', 'gramas'), ('ML', 'mL'), ('PITADA', 'pitada'), ('A GOSTO', 'a gosto')], max_length=10)),
                ('quantidade', models.CharField(max_length=5)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ingrediente.Ingrediente')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receita.Receita')),
            ],
        ),
    ]
