# Generated by Django 3.0.5 on 2020-05-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitaIngrediente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitaingrediente',
            name='unidade',
            field=models.CharField(choices=[('UN', 'unidade'), ('XICARA', 'xícara'), ('TSP', 'colher de chá'), ('TBSP', 'colher de sopa'), ('G', 'gramas'), ('ML', 'mL'), ('PITADA', 'pitada'), ('A GOSTO', 'a gosto'), ('CAIXA', 'caixa'), ('LATA', 'lata')], max_length=10),
        ),
    ]
