# Generated by Django 3.0.5 on 2020-05-08 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0003_remove_ingrediente_unidade'),
        ('receitaIngrediente', '0002_auto_20200507_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitaingrediente',
            name='ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingrediente.Ingrediente'),
        ),
    ]
