# Generated by Django 3.0.5 on 2020-05-23 00:29

from django.db import migrations
import enumfields.fields
import receitas.receitaIngrediente.models


class Migration(migrations.Migration):

    dependencies = [
        ('receitaIngrediente', '0003_auto_20200508_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitaingrediente',
            name='unidade',
            field=enumfields.fields.EnumField(default='unidade', enum=receitas.receitaIngrediente.models.Unidade, max_length=55),
        ),
    ]
