# Generated by Django 3.0.5 on 2020-04-29 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingrediente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_de_preparo', models.TextField()),
                ('dificuldade', models.CharField(max_length=1)),
                ('ingredientes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ingrediente.Ingrediente')),
            ],
        ),
    ]
