# Generated by Django 3.0.5 on 2020-04-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='nome',
            field=models.CharField(default='Receita X', max_length=50),
        ),
    ]
