# Generated by Django 3.0.5 on 2020-05-07 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0003_auto_20200429_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='ingredientes',
        ),
    ]
