# Generated by Django 3.0.5 on 2020-05-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0004_remove_receita_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('GE', 'Geral'), ('SO', 'Sobremesas'), ('SA', 'Salgados'), ('BO', 'Bolos'), ('AC', 'Acompanhamento')], default='GE', max_length=2),
        ),
        migrations.AlterField(
            model_name='receita',
            name='dificuldade',
            field=models.CharField(choices=[('MF', 'muito fácil'), ('F', 'fácil'), ('M', 'médio'), ('D', 'difícil'), ('MD', 'muito difícil')], default='M', max_length=2),
        ),
    ]
