# Generated by Django 3.0.5 on 2020-05-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0005_auto_20200519_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('GE', 'Geral'), ('SO', 'Sobremesas'), ('SA', 'Salgados'), ('BO', 'Bolos'), ('AC', 'Acompanhamentos')], default='GE', max_length=2),
        ),
    ]
