# Generated by Django 3.0.5 on 2020-05-22 23:03

from django.db import migrations
import enumfields.fields
import receitas.receita.models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0006_auto_20200519_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=enumfields.fields.EnumField(default='Geral', enum=receitas.receita.models.Categorias, max_length=10),
        ),
        migrations.AlterField(
            model_name='receita',
            name='dificuldade',
            field=enumfields.fields.EnumField(default='M', enum=receitas.receita.models.Dificuldade, max_length=10),
        ),
    ]
