# Generated by Django 3.0.5 on 2020-05-22 23:53

from django.db import migrations
import enumfields.fields
import receitas.receita.models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0009_auto_20200522_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=enumfields.fields.EnumField(default='Geral', enum=receitas.receita.models.Categorias, max_length=55),
        ),
        migrations.AlterField(
            model_name='receita',
            name='dificuldade',
            field=enumfields.fields.EnumField(default='médio', enum=receitas.receita.models.Dificuldade, max_length=55),
        ),
    ]
