# Generated by Django 3.0.5 on 2020-06-16 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0010_auto_20200522_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='modo_de_preparo',
        ),
    ]
