# Generated by Django 3.0.5 on 2020-06-16 02:55

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import receitas.ingrediente.models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0011_remove_receita_modo_de_preparo'),
        ('ingrediente', '0003_remove_ingrediente_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='quantidade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='receita',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='receita.Receita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='substituto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='unidade',
            field=enumfields.fields.EnumField(default='unidade', enum=receitas.ingrediente.models.Unidade, max_length=55),
        ),
    ]
